/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.fedproxy.rbac'

export { $nsid }

/** RBAC policy record granting a requester the ability to register SSH public keys under a specific fedproxy service tunnel. Roles define OIDC token claims that authorize the holder; policies define JSON Schema constraints on com.atproto.repo.createRecord for com.fedproxy.sshPublicKey records. */
type Main = {
  $type: 'com.fedproxy.rbac'

  /**
   * Map of role name → role definition. Each role defines OIDC claim constraints (aud, iss, sub) and references a policy name.
   */
  roles: l.LexMap

  /**
   * Map of policy name → policy definition. Each policy defines a JSON Schema over com.atproto.repo.createRecord for com.fedproxy.sshPublicKey.
   */
  policies: l.LexMap

  /**
   * Index mapping custom claim keys to role names for fast OIDC token validation lookup.
   */
  custom_claims_roles_index?: l.LexMap
  createdAt: l.DatetimeString
}

export type { Main }

/** RBAC policy record granting a requester the ability to register SSH public keys under a specific fedproxy service tunnel. Roles define OIDC token claims that authorize the holder; policies define JSON Schema constraints on com.atproto.repo.createRecord for com.fedproxy.sshPublicKey records. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    roles: /*#__PURE__*/ l.lexMap(),
    policies: /*#__PURE__*/ l.lexMap(),
    custom_claims_roles_index: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.lexMap(),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
