/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as ComputeVm from '../compute/vm.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.gateway.requestComputeVM'

export { $nsid }

export const $params = /*#__PURE__*/ l.params()

export type $Params = l.InferOutput<typeof $params>

export const $input = /*#__PURE__*/ l.jsonPayload({
  computeVm: /*#__PURE__*/ l.ref<ComputeVm.Main>((() => ComputeVm.main) as any),
  sshPublicKey: /*#__PURE__*/ l.string(),
  vmReadyTimeoutSec: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  execProgram: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.string(), 'bash'),
  ),
  skipSsh: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
  ),
  keepVm: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.boolean(), true),
  ),
  policy: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.ref<PolicySpec>((() => policySpec) as any),
  ),
  policyEngine: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  extraBidderDids: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'did' })),
  ),
})

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>

export const $output = /*#__PURE__*/ l.jsonPayload({
  receiptUri: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'at-uri' }),
  ),
  receiptCid: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'cid' }),
  ),
  receiptOk: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
  sshReady: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
  sshExitCode: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  websocatUrl: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'uri' }),
  ),
  vmFqdn: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  winnerDid: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'did' }),
  ),
  winnerBidUri: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'at-uri' }),
  ),
  winnerBidCid: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'cid' }),
  ),
  winnerBidConfig: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
  rfpUri: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'at-uri' }),
  ),
  rfpCid: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'cid' })),
  bids: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<BidSummary>((() => bidSummary) as any),
    ),
  ),
  error: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Request a VM through the compute contract gateway. Gateway builds cloud-init from sshPublicKey, creates compute.vm and market.rfp records, discovers bidders, runs the full RFP protocol, submits accept, and verifies the receipt. Returns receipt refs and websocatUrl for SSH access. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  'InvalidRequest',
  'AuthRequired',
  'NoBidders',
  'ProvisioningFailed',
])

export { main }

export const $lxm = $nsid

type PolicySpec = {
  $type?: 'com.publicdomainrelay.temp.gateway.requestComputeVM#policySpec'

  /**
   * Registry name of the policy to run (for example only-me, tangled-vouch, mutuals).
   */
  name: string

  /**
   * Human-readable description of what this policy admits.
   */
  description?: string

  /**
   * Arguments passed to the policy. Well-known keys: bidWindowSec, firstFree.
   */
  args?: l.LexMap
}

export type { PolicySpec }

const policySpec = /*#__PURE__*/ l.typedObject<PolicySpec>(
  $nsid,
  'policySpec',
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string(),
    description: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    args: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
  }),
)

export { policySpec }

type BidSummary = {
  $type?: 'com.publicdomainrelay.temp.gateway.requestComputeVM#bidSummary'
  bidderDid?: l.DidString
  bidUri?: l.AtUriString
  cost?: number
}

export type { BidSummary }

const bidSummary = /*#__PURE__*/ l.typedObject<BidSummary>(
  $nsid,
  'bidSummary',
  /*#__PURE__*/ l.object({
    bidderDid: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'did' }),
    ),
    bidUri: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'at-uri' }),
    ),
    cost: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.integer()),
  }),
)

export { bidSummary }
