/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid =
  'com.publicdomainrelay.temp.gateway.requestComputeWorkerPersistent'

export { $nsid }

export const $params = /*#__PURE__*/ l.params()

export type $Params = l.InferOutput<typeof $params>

export const $input = /*#__PURE__*/ l.jsonPayload({
  source: /*#__PURE__*/ l.string(),
  denoJson: /*#__PURE__*/ l.string(),
  denoLock: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  bidWindowSec: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(/*#__PURE__*/ l.integer(), 30),
  ),
})

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>

export const $output = /*#__PURE__*/ l.jsonPayload({
  receiptUri: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'at-uri' }),
  ),
  receiptCid: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'cid' }),
  ),
  receiptOk: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.boolean()),
  workerInstanceUri: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'at-uri' }),
  ),
  executeUrl: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'uri' }),
  ),
  error: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Request a persistent Deno worker through the compute contract gateway. Gateway bundles source, creates workerManifest record, runs the full RFP protocol, starts the worker, and returns the worker instance ref and execute URL. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  'InvalidRequest',
  'AuthRequired',
  'NoBidders',
])

export { main }

export const $lxm = $nsid
