/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.gateway.subscribeComputeEvents'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  receiptUri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
})

export type $Params = l.InferOutput<typeof $params>

export const $message = /*#__PURE__*/ l.typedUnion(
  [
    /*#__PURE__*/ l.typedRef<Vm_started>((() => vm_started) as any),
    /*#__PURE__*/ l.typedRef<Vm_on_network>((() => vm_on_network) as any),
    /*#__PURE__*/ l.typedRef<Terminated>((() => terminated) as any),
    /*#__PURE__*/ l.typedRef<Error>((() => error) as any),
  ],
  false,
)

export type $Message = l.InferOutput<typeof $message>

/** Subscribe to lifecycle events for a compute contract. Gateway pushes events as they arrive from the bidder (vm.started, vm.onNetwork, terminated). */
const main = /*#__PURE__*/ l.subscription($nsid, $params, $message, [
  'InvalidRequest',
  'AuthRequired',
])

export { main }

export const $lxm = $nsid

type Vm_started = {
  $type?: 'com.publicdomainrelay.temp.gateway.subscribeComputeEvents#vm_started'
  receiptUri: l.AtUriString
  timestamp: l.DatetimeString
}

export type { Vm_started as VmStarted }

const vm_started = /*#__PURE__*/ l.typedObject<Vm_started>(
  $nsid,
  'vm_started',
  /*#__PURE__*/ l.object({
    receiptUri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    timestamp: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { vm_started }

type Vm_on_network = {
  $type?: 'com.publicdomainrelay.temp.gateway.subscribeComputeEvents#vm_on_network'
  receiptUri: l.AtUriString
  address: string
  timestamp: l.DatetimeString
}

export type { Vm_on_network as VmOnNetwork }

const vm_on_network = /*#__PURE__*/ l.typedObject<Vm_on_network>(
  $nsid,
  'vm_on_network',
  /*#__PURE__*/ l.object({
    receiptUri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    address: /*#__PURE__*/ l.string(),
    timestamp: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { vm_on_network }

type Terminated = {
  $type?: 'com.publicdomainrelay.temp.gateway.subscribeComputeEvents#terminated'
  receiptUri: l.AtUriString
  reason: string
  timestamp: l.DatetimeString
}

export type { Terminated }

const terminated = /*#__PURE__*/ l.typedObject<Terminated>(
  $nsid,
  'terminated',
  /*#__PURE__*/ l.object({
    receiptUri: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    reason: /*#__PURE__*/ l.string(),
    timestamp: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { terminated }

type Error = {
  $type?: 'com.publicdomainrelay.temp.gateway.subscribeComputeEvents#error'
  message: string
}

export type { Error }

const error = /*#__PURE__*/ l.typedObject<Error>(
  $nsid,
  'error',
  /*#__PURE__*/ l.object({ message: /*#__PURE__*/ l.string() }),
)

export { error }
