apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: hono-compute-contract-gateway-c2s-05fe29612a62-05fe29612a62
  namespace: default
spec:
  systemContext: hono-compute-contract-gateway
  direction: CodeToSpec
  fromCommit: 05fe29612a62a645d70273560238ecc3180414d2
  toCommit: 05fe29612a62a645d70273560238ecc3180414d2
status:
  phase: Pending
  message: waiting for the agent that summarizes hono-compute-contract-gateway
