apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: lib-market-settlement-free-c2s-d20070c3bfb0-d20070c3bfb0
  namespace: default
spec:
  delta: {}
  direction: CodeToSpec
  fromCommit: d20070c3bfb0922fa261d6fc217f8bdfb931311b
  systemContext: lib-market-settlement-free
  toCommit: d20070c3bfb0922fa261d6fc217f8bdfb931311b
status:
  message: the agent is summarizing lib-market-settlement-free
  phase: Running
