apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: lib-common-compute-contract-gateway-common-c2s-05fe29612a62-05fe29612a62
  namespace: default
spec:
  systemContext: lib-common-compute-contract-gateway-common
  direction: CodeToSpec
  fromCommit: 05fe29612a62a645d70273560238ecc3180414d2
  toCommit: 05fe29612a62a645d70273560238ecc3180414d2
status:
  phase: Running
  message: the agent is summarizing lib-common-compute-contract-gateway-common
