apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: lib-common-cloud-init-common-s2c-94ec68de1a7b
  namespace: default
spec:
  systemContext: lib-common-cloud-init-common
  direction: SpecToCode
  fromSpecHash: 980697081a9d94f9872c2c041f7b662d36ef9756b4036d014fd96a44fb35fa75
  toSpecHash: 94ec68de1a7b00237e7b2317847f02d55f58a4c99a1744ac568759487e78ef3d
  delta:
    counts:
      changed: 1
    requirements:
    - ~r.iroh-ticket-report
status:
  phase: Pending
