apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SpecChange
metadata:
  name: lib-did-plc-generated-client-c2s-8b36a2bfe627-8b36a2bfe627
  namespace: default
spec:
  systemContext: lib-did-plc-generated-client
  direction: CodeToSpec
  fromCommit: 8b36a2bfe627f7128cc32482542ecaf1718a2577
  toCommit: 8b36a2bfe627f7128cc32482542ecaf1718a2577
status:
  phase: Running
  message: the agent is summarizing lib-did-plc-generated-client
