/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from '../../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.policies.builtin'

export { $nsid }

/** Fulfillment policy set evaluated by pre-defined, first-party policies named in the evaluator's registry. Executed in an in-process Deno worker sandbox with no permissions; all record resolution is brokered by the host. Carries downstream through subcontracting chains. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.policies.builtin'

  /**
   * Named policies to evaluate; all must allow.
   */
  policies: PolicySpec[]

  /**
   * ATProto DID of the root requester this policy set was minted for.
   */
  requesterDid: string
  createdAt: l.DatetimeString

  /**
   * badge.blue attestations over this policy.
   */
  signatures?: AttestedSignature.Signatures
}

export type { Main }

/** Fulfillment policy set evaluated by pre-defined, first-party policies named in the evaluator's registry. Executed in an in-process Deno worker sandbox with no permissions; all record resolution is brokered by the host. Carries downstream through subcontracting chains. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    policies: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<PolicySpec>((() => policySpec) as any),
    ),
    requesterDid: /*#__PURE__*/ l.string(),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    signatures: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
        (() => AttestedSignature.signatures) as any,
      ),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type PolicySpec = {
  $type?: 'com.publicdomainrelay.temp.market.policies.builtin#policySpec'

  /**
   * Registry name of the policy to run (for example only-me, tangled-vouch, mutuals, under-4-cpus).
   */
  name: string

  /**
   * Human-readable description of what this policy admits.
   */
  description?: string

  /**
   * Arguments passed to the policy. Well-known keys: bidWindowSec, firstFree.
   */
  args?: l.LexMap
}

export type { PolicySpec }

const policySpec = /*#__PURE__*/ l.typedObject<PolicySpec>(
  $nsid,
  'policySpec',
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string(),
    description: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    args: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
  }),
)

export { policySpec }
