/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 * @ts-nocheck — l.ref() inferred input types are over-strict with optional ref fields
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from '../../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.policies.direct_network'

export { $nsid }

/** Fulfillment policy: only bidders whose operator DID appears in the requester's direct vouch network may bid. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.policies.direct_network'

  /**
   * ATProto DID of the root requester. The vouch graph is traversed starting from this DID.
   */
  requesterDid: string

  /**
   * NSID of the vouch collection to traverse (e.g. sh.tangled.graph.vouch).
   */
  vouchNsid: string

  /**
   * Maximum depth of vouch graph traversal. 1 = direct vouches only.
   */
  maxDepth: number

  /**
   * badge.blue attestations over this policy. Must include the requester's inline signature, attached at creation.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** Fulfillment policy: only bidders whose operator DID appears in the requester's direct vouch network may bid. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    requesterDid: /*#__PURE__*/ l.string(),
    vouchNsid: /*#__PURE__*/ l.string(),
    maxDepth: /*#__PURE__*/ l.integer(),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
