/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as AttestedSignature from '../../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.policies.service'

export { $nsid }

/** Fulfillment policy set evaluated by a remote policy engine. The evaluator signs a service-auth JWT and calls com.publicdomainrelay.temp.market.evaluatePolicy on the engine, passing each policy name and its arguments. Carries downstream through subcontracting chains. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.policies.service'

  /**
   * Named policies for the engine to run; all must allow.
   */
  policies: PolicySpec[]

  /**
   * DID of the policy engine that evaluates this policy (for example did:web:engine.example.com).
   */
  policyEngine: string

  /**
   * ATProto DID of the root requester this policy set was minted for.
   */
  requesterDid: string
  createdAt: l.DatetimeString

  /**
   * badge.blue attestations over this policy.
   */
  signatures?: AttestedSignature.Signatures
}

export type { Main }

/** Fulfillment policy set evaluated by a remote policy engine. The evaluator signs a service-auth JWT and calls com.publicdomainrelay.temp.market.evaluatePolicy on the engine, passing each policy name and its arguments. Carries downstream through subcontracting chains. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    policies: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<PolicySpec>((() => policySpec) as any),
    ),
    policyEngine: /*#__PURE__*/ l.string(),
    requesterDid: /*#__PURE__*/ l.string(),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    signatures: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
        (() => AttestedSignature.signatures) as any,
      ),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type PolicySpec = {
  $type?: 'com.publicdomainrelay.temp.market.policies.service#policySpec'

  /**
   * Name of the policy for the engine to run. Engines resolve this against the same registry used for local execution.
   */
  name: string

  /**
   * Human-readable description of what this policy admits.
   */
  description?: string

  /**
   * Arguments passed to the policy at evaluation time. Well-known keys: bidWindowSec, firstFree.
   */
  args?: l.LexMap
}

export type { PolicySpec }

const policySpec = /*#__PURE__*/ l.typedObject<PolicySpec>(
  $nsid,
  'policySpec',
  /*#__PURE__*/ l.object({
    name: /*#__PURE__*/ l.string(),
    description: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    args: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.lexMap()),
  }),
)

export { policySpec }
