/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 * @ts-nocheck — l.ref() inferred input types are over-strict with optional ref fields
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.policies.workflow_gha'

export { $nsid }

/** Fulfillment policy: runs a GitHub Actions workflow via the policy-engine for maximum configurability. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.policies.workflow_gha'

  /**
   * ATProto DID of the root requester. Passed as input to the workflow evaluation.
   */
  requesterDid: string

  /**
   * Strong reference to a workflow definition record — the GHA workflow that evaluates bidder eligibility.
   */
  workflowRef: RepoStrongRef.Main

  /**
   * URL of the policy-engine that executes the workflow.
   */
  engineUrl: string

  /**
   * badge.blue attestations over this policy. Must include the requester's inline signature, attached at creation.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** Fulfillment policy: runs a GitHub Actions workflow via the policy-engine for maximum configurability. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    requesterDid: /*#__PURE__*/ l.string(),
    workflowRef: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    engineUrl: /*#__PURE__*/ l.string(),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
