/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.badgeBlueKeys'

export { $nsid }

/** Associates a device key with a DID, enabling key->DID lookup for vouch graph traversal and service authorization. */
type Main = {
  $type: 'com.publicdomainrelay.temp.badgeBlueKeys'

  /**
   * Identifier for the device key (e.g. soft-<uuid> or a did:key).
   */
  keyId: string

  /**
   * Human-readable name or label for this key association (e.g. hostname).
   */
  name?: string

  /**
   * DID that this key is bound to.
   */
  challenge: l.DidString

  /**
   * Service scope for this key association.
   */
  service?: string
  createdAt: l.DatetimeString
}

export type { Main }

/** Associates a device key with a DID, enabling key->DID lookup for vouch graph traversal and service authorization. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    keyId: /*#__PURE__*/ l.string(),
    name: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    challenge: /*#__PURE__*/ l.string({ format: 'did' }),
    service: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
