/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.compute.events.vm.onNetwork'

export { $nsid }

/** Reports that a provisioned VM has come up on the network and is reachable (e.g. it registered its SSH key / fedproxy route and its policy engine answered). */
type Main = {
  $type: 'com.publicdomainrelay.temp.compute.events.vm.onNetwork'

  /**
   * Informational, non-routable address of the provisioned VM (a container or droplet IP), or a relay FQDN under the legacy tunnel/fedproxy-ssh transports. Never the guest's iroh ticket, its endpoint id, or any address that dials the guest: this record is world-readable and the ticket is the capability that reaches the guest's sshd.
   */
  address?: string
  createdAt: l.DatetimeString
}

export type { Main }

/** Reports that a provisioned VM has come up on the network and is reachable (e.g. it registered its SSH key / fedproxy route and its policy engine answered). */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    address: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
