/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.compute.events.vm.registerIdentity'

export { $nsid }

/** Reports a guest compute identity (DID + FQDN) so the requester can reach the guest through the relay. */
type Main = {
  $type: 'com.publicdomainrelay.temp.compute.events.vm.registerIdentity'

  /** The guest's DID (did:plc or did:key). */
  did: string

  /** The guest's FQDN reachable through the relay dispatcher. */
  fqdn: string

  /** Transport type: "tunnel" (did-key-ingress-proxy) or "fedproxy". */
  transport?: string

  createdAt: l.DatetimeString
}

export type { Main }

/** Reports a guest compute identity (DID + FQDN) so the requester can reach the guest through the relay. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    did: /*#__PURE__*/ l.string(),
    fqdn: /*#__PURE__*/ l.string(),
    transport: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
