// Pure interfaces for the compute requester. Zero I/O, no Deno.*, no fetch, no crypto.
// Depends on market-common + serve/logger types only (type-level imports).

import type { StructuredLoggerInterface } from "@publicdomainrelay/logger";
import type { IngressRef, ServeHandle } from "@publicdomainrelay/serve";

export interface CollectedBid {
  did: string;
  uri: string;
  cid: string;
  record: Record<string, unknown>;
}

export interface ContractFlowOptions {
  vmName?: string;
  plcUrl?: string;
  /**
   * Extra `/etc/hosts` entries ("<ip> <name>") for the guest, so it can dial the
   * dispatcher by a name that also resolves for this requester.
   */
  guestHostAliases?: string[];
  /** Atproto relay URLs for bidder discovery via listReposByCollection. */
  relayUrls?: string[];
  /** Additional bidder DIDs beyond those discovered via relay + vouch. */
  extraBidderDids?: string[];
  /** DIDs to exclude from bidding, even if discovered. */
  denyBidderDids?: string[];
  skipSsh?: boolean;
  execProgram?: string;
  keepVm?: boolean;
  vmReadyTimeoutSec?: number;
  onSshStart?: () => void;
  onSshEnd?: () => void | Promise<void>;
  /**
   * Overrides the ssh ProxyCommand per guest FQDN (default:
   * `websocat --binary wss://<fqdn>`). Lets tests and alternate ingress
   * topologies rewrite the tunnel endpoint while keeping the RFP flow intact.
   */
  sshProxyCommandFn?: (fqdn: string) => string;
  /**
   * XRPC dispatcher host: the atproto/WS relay plane the requester and guest
   * subscribe to (e.g. xrpc.fedproxy.com). Carries createRecord/submitRfp.
   */
  ingressProxyHost?: string;
  /**
   * FedProxy SSH-tunnel host: the raw ssh/tcp ingress where the guest's
   * fedproxy-client publishes itself as <vmName>--did-plc-<key>.<fedingressHost>
   * (e.g. fedproxy.com). Distinct from ingressProxyHost in production; the VM
   * FQDN polled for SSH is derived from this. Defaults to fedproxy.com. In the
   * hermetic test a single local relay serves both planes, so it is set to the
   * test dispatcher host.
   */
  fedingressHost?: string;
  /**
   * When set, replaces the default cloud-init generator
   * (buildDefaultUserData) to allow custom guest-side transport.
   * the ssh authorized key generated by the sshProvider; the caller closes
   * over any additional context. Returns a #cloud-config YAML string.
   */
  userDataFactory?: (sshAuthorizedKey: string) => string;
  /**
   * Caller-supplied base cloud-config (e.g. read from a --user-data file). When
   * set, the default websocat/fedproxy-client provisioning is patched into this
   * base (patchDefaultUserData) rather than generating a fresh cloud-config --
   * mirrors how compute-providers patch user_data. Ignored when userDataFactory
   * is set (that fully replaces the cloud-init).
   */
  baseUserData?: string;
  /**
   * When true, after the winning bid is selected the requester resolves the
   * winner's bidConfig (wif.simple) and writes a com.fedproxy.rbac record into
   * its own repo, authorizing the VM (by wif subject) to createRecord the
   * com.fedproxy.sshPublicKey record for this VM's service name. Default off so
   * headless/container tests are unaffected; the CLI enables it by default.
   */
  rbac?: boolean;
  appliesToNsid?: string;
  /**
   * Fulfillment policy to mint and attach to the RFP. Its args carry the
   * knobs that used to be separate flags -- bidWindowSec, firstFree.
   */
  policy?: import("@publicdomainrelay/market-policy-abc").PolicySpec;
  /** DID of a remote policy engine. Set to mint a policies.service record. */
  policyEngine?: string;
  /** Refuse to evaluate any non-service policy record locally. */
  onlyRemotePolicyExec?: boolean;
  /** Permit policies.denoWorker records to run caller-supplied bundles. */
  allowUntrustedPolicyExec?: boolean;
}

export interface PDSOptions {
  logger: StructuredLoggerInterface;
  serve: ServeHandle;
  privateKeyHex?: string;
  plcDirectoryUrl?: string;
  ingressProxyHost?: string;
  label?: string;
  storagePath?: string;
  skipIngress?: boolean;
}

export interface RequesterPDS {
  did: string;
  serve: ServeHandle;
  relay: IngressRef;
  /** Valid only after beginServe(); reads lazily off the relay. */
  ingressRef: string;
  /** Valid only after beginServe(). */
  relaySubdomain: string;
  /** Valid only after beginServe(). Returns "" before relay connects. */
  ingressUrl: string;
  /** Valid only after beginServe(). Returns "" before relay connects. */
  ingressHost: string;
  beginServe(): Promise<void>;
  pendingBids: Map<string, CollectedBid[]>;
  createRepoRecord(collection: string, record: Record<string, unknown>): Promise<{ uri: string; cid: string }>;
  createSignedRepoRecord(
    collection: string,
    record: Record<string, unknown>,
    aKp: { did(): string; privateKey: { bytes: Uint8Array; toBytes?(): Uint8Array } },
    issuer?: string,
  ): Promise<{ uri: string; cid: string }>;
  resolveBidderEndpoint(endpointUrl: string): Promise<{ targetUrl: string; audDid: string } | null>;
  callBidder(
    targetBase: string,
    nsid: string,
    lxm: string,
    audDid: string,
    body: Record<string, unknown>,
  ): Promise<{ status: number; ok: boolean; body: unknown }>;
  attestationKp: { did(): string; privateKey: { bytes: Uint8Array; toBytes?(): Uint8Array } };
  signer: { did(): string; sign(bytes: Uint8Array): Promise<Uint8Array> };
  privateKeyHex: string;
  /** Resolves with caller DID when webapp calls associateConfirm XRPC. */
  associateCalled: Promise<string>;
  /** Call after CLI user confirms association. Resolves the pending XRPC response. */
  approveAssociation(): void;
  /** Call if CLI user rejects association. Rejects the pending XRPC response. */
  rejectAssociation(err: Error): void;
  /** Release storage resources (close Deno.Kv if using DenoKvStorage). */
  dispose(): Promise<void>;
  /** iroh nodeId promise -- resolves when guest publishes its identity via firehose. */
  irohNodeId?: Promise<string>;
  /** Resolve the iroh nodeId promise. No-op after first call. */
  resolveIrohNodeId?(nodeId: string): void;
  /** Set callback invoked when guest-side onNetwork event arrives via submitEvent XRPC. */
  setOnNetworkResolved?(fn: (address: string) => void): void;
}

export interface SshSessionProvider {
  generateKeypair(vmName: string): Promise<{ publicKey: string; privateKeyPath: string }>;
  pollReady(privateKeyPath: string, fqdn: string, timeoutMs: number): Promise<boolean>;
  runSession(privateKeyPath: string, fqdn: string, program: string): Promise<number>;
}

export interface ContractFlowResult {
  event: string;
  vmUri?: string;
  vmCid?: string;
  rfpUri?: string;
  rfpCid?: string;
  acceptUri?: string;
  acceptCid?: string;
  bidUri?: string;
  bidCid?: string;
  winnerDid?: string;
  receiptUri?: string;
  receiptCid?: string;
  submitEventRef?: string;
  receiptOk?: boolean;
  bids?: number;
  error?: string;
  sshReady?: boolean;
  sshExitCode?: number;
}

export interface ConsoleBuffer {
  pause(): void;
  resume(): Promise<void>;
}

export function bidPayloadNsid(bid: CollectedBid): string {
  const payload = bid.record.payload as { $type?: string; uri?: string } | undefined;
  if (!payload) return "";
  if (payload.$type && payload.$type !== "com.atproto.repo.strongRef") return payload.$type;
  return payload.uri?.split("/")[3] ?? "";
}

export function bidCost(bid: CollectedBid): number {
  const payload = bid.record.payload as Record<string, unknown> | undefined;
  return Number(payload?.cost ?? Infinity);
}

export function selectWinner(bids: CollectedBid[]): CollectedBid | undefined {
  if (bids.length === 0) return undefined;
  return bids.reduce((best, b) => (bidCost(b) < bidCost(best) ? b : best), bids[0]);
}

export interface BidCollectorOptions {
  /** NSID that marks a bid as free, e.g. com.publicdomainrelay.temp.market.bids.free */
  freeBidNsid: string;
  firstFree: boolean;
  /**
   * Policy gate for the early-exit path. A free bid only wins immediately if
   * this resolves true, so a free bid from a rejected bidder never short
   * circuits the window.
   */
  allow: (bid: CollectedBid) => Promise<boolean>;
  onEarlyWinner?: (bid: CollectedBid) => void;
}

/**
 * Pure bid accumulator. Dedupes by URI and, when firstFree is set, resolves
 * earlyWinner as soon as a policy-allowed free bid arrives so the caller can
 * stop waiting out the bid window.
 */
export class BidCollector {
  readonly earlyWinner: Promise<CollectedBid>;
  #resolveEarly!: (bid: CollectedBid) => void;
  #seen = new Set<string>();
  #bids: CollectedBid[] = [];
  #settled = false;
  #inflight = new Set<Promise<void>>();

  constructor(readonly opts: BidCollectorOptions) {
    const { promise, resolve } = Promise.withResolvers<CollectedBid>();
    this.earlyWinner = promise;
    this.#resolveEarly = resolve;
  }

  isFree(bid: CollectedBid): boolean {
    return bidPayloadNsid(bid) === this.opts.freeBidNsid;
  }

  add(bid: CollectedBid): void {
    if (this.#seen.has(bid.uri)) return;
    this.#seen.add(bid.uri);
    this.#bids.push(bid);

    if (!this.opts.firstFree || this.#settled || !this.isFree(bid)) return;

    const check = this.opts.allow(bid)
      .then((ok) => {
        if (!ok || this.#settled) return;
        this.#settled = true;
        this.opts.onEarlyWinner?.(bid);
        this.#resolveEarly(bid);
      })
      .catch(() => {});
    this.#inflight.add(check);
    check.finally(() => this.#inflight.delete(check));
  }

  addAll(bids: CollectedBid[]): void {
    for (const bid of bids) this.add(bid);
  }

  all(): CollectedBid[] {
    return this.#bids;
  }

  /** Wait for any in-flight early-path policy checks to settle. */
  async drain(): Promise<void> {
    while (this.#inflight.size > 0) {
      await Promise.allSettled([...this.#inflight]);
    }
  }
}
