// Pure interfaces for the compute requester. Zero I/O, no Deno.*, no fetch, no crypto.
// Depends on market-common + serve/logger types only (type-level imports).

import type { StructuredLoggerInterface } from "@publicdomainrelay/logger";
import type { IngressRef, ServeHandle } from "@publicdomainrelay/serve";

export interface CollectedBid {
  did: string;
  uri: string;
  cid: string;
  record: Record<string, unknown>;
}

export interface ContractFlowOptions {
  vmName?: string;
  bidWindowSec?: number;
  plcUrl?: string;
  /** Atproto relay URLs for bidder discovery via listReposByCollection. */
  relayUrls?: string[];
  /** Additional bidder DIDs beyond those discovered via relay + vouch. */
  extraBidderDids?: string[];
  /** DIDs to exclude from bidding, even if discovered. */
  denyBidderDids?: string[];
  skipSsh?: boolean;
  execProgram?: string;
  keepVm?: boolean;
  vmReadyTimeoutSec?: number;
  onSshStart?: () => void;
  onSshEnd?: () => void | Promise<void>;
  /**
   * Overrides the ssh ProxyCommand per guest FQDN (default:
   * `websocat --binary wss://<fqdn>`). Lets tests and alternate ingress
   * topologies rewrite the tunnel endpoint while keeping the RFP flow intact.
   */
  sshProxyCommandFn?: (fqdn: string) => string;
  /**
   * XRPC dispatcher host: the atproto/WS relay plane the requester and guest
   * subscribe to (e.g. xrpc.fedproxy.com). Carries createRecord/submitRfp.
   */
  ingressProxyHost?: string;
  /**
   * FedProxy SSH-tunnel host: the raw ssh/tcp ingress where the guest's
   * fedproxy-client publishes itself as <vmName>--did-plc-<key>.<fedingressHost>
   * (e.g. fedproxy.com). Distinct from ingressProxyHost in production; the VM
   * FQDN polled for SSH is derived from this. Defaults to fedproxy.com. In the
   * hermetic test a single local relay serves both planes, so it is set to the
   * test dispatcher host.
   */
  fedingressHost?: string;
  /**
   * When set, replaces the default cloud-init generator
   * (buildDefaultUserData) to allow custom guest-side transport.
   * the ssh authorized key generated by the sshProvider; the caller closes
   * over any additional context. Returns a #cloud-config YAML string.
   */
  userDataFactory?: (sshAuthorizedKey: string) => string;
  /**
   * Caller-supplied base cloud-config (e.g. read from a --user-data file). When
   * set, the default websocat/fedproxy-client provisioning is patched into this
   * base (patchDefaultUserData) rather than generating a fresh cloud-config —
   * mirrors how compute-providers patch user_data. Ignored when userDataFactory
   * is set (that fully replaces the cloud-init).
   */
  baseUserData?: string;
  /**
   * When true, after the winning bid is selected the requester resolves the
   * winner's bidConfig (wif.simple) and writes a com.fedproxy.rbac record into
   * its own repo, authorizing the VM (by wif subject) to createRecord the
   * com.fedproxy.sshPublicKey record for this VM's service name. Default off so
   * headless/container tests are unaffected; the CLI enables it by default.
   */
  rbac?: boolean;
  appliesToNsid?: string;
  policyMode?: import("@publicdomainrelay/market-policy-abc").PolicyMode;
  policyEngineEndpoint?: string;
  /**
   * Guest transport: "iroh" (P2P, default), "fedproxy" (websocat + fedproxy-client),
   * or "tunnel-subscriber" (xrpc relay tunnel).
   */
  transport?: "iroh" | "fedproxy" | "tunnel-subscriber";
  /**
   * Relay hostname for JWT service-auth audience (did:web:<audHost>).
   * Only used with transport=tunnel-subscriber. Auto-derived from
   * ingressProxyHost (strip port) when unset.
   */
  tunnelSubscriberAudHost?: string;
}

export interface PDSOptions {
  logger: StructuredLoggerInterface;
  serve: ServeHandle;
  privateKeyHex?: string;
  plcDirectoryUrl?: string;
  ingressProxyHost?: string;
  label?: string;
  storagePath?: string;
  skipIngress?: boolean;
}

export interface RequesterPDS {
  did: string;
  serve: ServeHandle;
  relay: IngressRef;
  /** Valid only after beginServe(); reads lazily off the relay. */
  ingressRef: string;
  /** Valid only after beginServe(). */
  relaySubdomain: string;
  /** Valid only after beginServe(). Returns "" before relay connects. */
  ingressUrl: string;
  /** Valid only after beginServe(). Returns "" before relay connects. */
  ingressHost: string;
  beginServe(): Promise<void>;
  pendingBids: Map<string, CollectedBid[]>;
  createRepoRecord(collection: string, record: Record<string, unknown>): Promise<{ uri: string; cid: string }>;
  createSignedRepoRecord(
    collection: string,
    record: Record<string, unknown>,
    aKp: { did(): string; privateKey: { bytes: Uint8Array; toBytes?(): Uint8Array } },
    issuer?: string,
  ): Promise<{ uri: string; cid: string }>;
  resolveBidderEndpoint(endpointUrl: string): Promise<{ targetUrl: string; audDid: string } | null>;
  callBidder(
    targetBase: string,
    nsid: string,
    lxm: string,
    audDid: string,
    body: Record<string, unknown>,
  ): Promise<{ status: number; ok: boolean; body: unknown }>;
  attestationKp: { did(): string; privateKey: { bytes: Uint8Array; toBytes?(): Uint8Array } };
  signer: { did(): string; sign(bytes: Uint8Array): Promise<Uint8Array> };
  privateKeyHex: string;
  /** Resolves with caller DID when webapp calls associateConfirm XRPC. */
  associateCalled: Promise<string>;
  /** Call after CLI user confirms association. Resolves the pending XRPC response. */
  approveAssociation(): void;
  /** Call if CLI user rejects association. Rejects the pending XRPC response. */
  rejectAssociation(err: Error): void;
  /** Release storage resources (close Deno.Kv if using DenoKvStorage). */
  dispose(): Promise<void>;
}

export interface SshSessionProvider {
  generateKeypair(vmName: string): Promise<{ publicKey: string; privateKeyPath: string }>;
  pollReady(privateKeyPath: string, fqdn: string, timeoutMs: number): Promise<boolean>;
  runSession(privateKeyPath: string, fqdn: string, program: string): Promise<number>;
}

export interface ContractFlowResult {
  event: string;
  vmUri?: string;
  vmCid?: string;
  rfpUri?: string;
  rfpCid?: string;
  acceptUri?: string;
  acceptCid?: string;
  bidUri?: string;
  bidCid?: string;
  winnerDid?: string;
  receiptUri?: string;
  receiptCid?: string;
  submitEventRef?: string;
  receiptOk?: boolean;
  bids?: number;
  error?: string;
  sshReady?: boolean;
  sshExitCode?: number;
}

export interface ConsoleBuffer {
  pause(): void;
  resume(): Promise<void>;
}
