/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.market.bidderDiscovery'

export { $nsid }

/** Published by a bidder in its own repo to announce availability. The bidder periodically updates `updatedAt` to signal liveness. The market registry polls this record to decide whether the bidder is still active. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.bidderDiscovery'

  /**
   * Service DID ref (e.g. did:web:HOST#pdr_temp_market) where submitRfp calls should be routed.
   */
  endpointUrl: string

  /**
   * Payload NSIDs this bidder handles (e.g. com.publicdomainrelay.temp.compute.vm).
   */
  appliesTo: l.NsidString[]

  /**
   * ISO 8601 timestamp of the last liveness update. The bidder updates this periodically; the registry treats a record as stale when updatedAt is older than a configured threshold (default 5 minutes).
   */
  updatedAt: l.DatetimeString
  createdAt: l.DatetimeString
}

export type { Main }

/** Published by a bidder in its own repo to announce availability. The bidder periodically updates `updatedAt` to signal liveness. The market registry polls this record to decide whether the bidder is still active. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    endpointUrl: /*#__PURE__*/ l.string(),
    appliesTo: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.string({ format: 'nsid' }),
      { minLength: 1 },
    ),
    updatedAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
