/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'
import * as RepoStrongRef from '../../../atproto/repo/strongRef.defs.ts'
import * as AttestedSignature from '../../../../network/attested/signature.defs.ts'

const $nsid = 'com.publicdomainrelay.temp.market.bidderAssociation'

export { $nsid }

/** Reverse pointer from a bidder's repo to the operator's badgeBlueKeys record. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.bidderAssociation'

  /**
   * ATProto DID of the operator who created the badgeBlueKeys record.
   */
  operatorDid: string

  /**
   * Strong reference to the operator's badgeBlueKeys record that associates this bidder's did:key with the operator's DID.
   */
  associationProof: RepoStrongRef.Main

  /**
   * badge.blue attestations over this association. Must include the bidder's inline signature, attached at creation.
   */
  signatures: AttestedSignature.Signatures
}

export type { Main }

/** Reverse pointer from a bidder's repo to the operator's badgeBlueKeys record. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    operatorDid: /*#__PURE__*/ l.string(),
    associationProof: /*#__PURE__*/ l.ref<RepoStrongRef.Main>(
      (() => RepoStrongRef.main) as any,
    ),
    signatures: /*#__PURE__*/ l.ref<AttestedSignature.Signatures>(
      (() => AttestedSignature.signatures) as any,
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
