/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.market.bidderRegistration'

export { $nsid }

/** An index entry in the market registry's repo tracking a registered bidder. The registry creates one entry per (bidderDid, payloadNsid) pair when a bidder calls registerBidder. Liveness is determined by polling the bidder's own bidderDiscovery record — this index entry carries no heartbeat timestamps. When a bidder goes stale the registry deletes its index entries. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.bidderRegistration'

  /**
   * DID of the registered bidder.
   */
  bidderDid: l.DidString

  /**
   * Payload NSIDs this bidder handles. Matches the appliesTo from the bidder's bidderDiscovery record at registration time.
   */
  appliesTo: l.NsidString[]

  /**
   * When the registry created this index entry.
   */
  indexedAt: l.DatetimeString
}

export type { Main }

/** An index entry in the market registry's repo tracking a registered bidder. The registry creates one entry per (bidderDid, payloadNsid) pair when a bidder calls registerBidder. Liveness is determined by polling the bidder's own bidderDiscovery record — this index entry carries no heartbeat timestamps. When a bidder goes stale the registry deletes its index entries. */
const main = /*#__PURE__*/ l.record<'any', Main>(
  'any',
  $nsid,
  /*#__PURE__*/ l.object({
    bidderDid: /*#__PURE__*/ l.string({ format: 'did' }),
    appliesTo: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.string({ format: 'nsid' }),
      { minLength: 1 },
    ),
    indexedAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
