/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.market.listBidders'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  payloadNsid: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.string({ format: 'nsid' }),
  ),
  maxResults: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 200 }),
      50,
    ),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  bidders: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<BidderItem>((() => bidderItem) as any),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** List active bidders indexed by the market registry. */
const main = /*#__PURE__*/ l.query($nsid, $params, $output, ['InvalidRequest'])

export { main }

export const $lxm = $nsid

type BidderItem = {
  $type?: 'com.publicdomainrelay.temp.market.listBidders#bidderItem'
  bidderDid: l.DidString
  appliesTo: string[]
}

export type { BidderItem }

const bidderItem = /*#__PURE__*/ l.typedObject<BidderItem>(
  $nsid,
  'bidderItem',
  /*#__PURE__*/ l.object({
    bidderDid: /*#__PURE__*/ l.string({ format: 'did' }),
    appliesTo: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string()),
  }),
)

export { bidderItem }
