/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.market.registerBidder'

export { $nsid }

export const $params = /*#__PURE__*/ l.params()

export type $Params = l.InferOutput<typeof $params>

export const $input = /*#__PURE__*/ l.jsonPayload({
  bidderDid: /*#__PURE__*/ l.string({ format: 'did' }),
  appliesTo: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'nsid' }), {
    minLength: 1,
  }),
})

export type $Input<B = l.BinaryData> = l.InferPayload<typeof $input, B>
export type $InputBody<B = l.BinaryData> = l.InferPayloadBody<typeof $input, B>

export const $output = /*#__PURE__*/ l.jsonPayload({
  ok: /*#__PURE__*/ l.boolean(),
  registrationUri: /*#__PURE__*/ l.string(),
  registrationCid: /*#__PURE__*/ l.string(),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Register a bidder with the market registry. Called by bidders after they publish a bidderDiscovery record in their own repo and connect to the relay. The registry verifies the caller's service-auth JWT issuer matches the bidderDid, then indexes the bidder so it appears in listBidders queries. Liveness is determined by the registry polling the bidder's bidderDiscovery record — there is no separate heartbeat procedure. */
const main = /*#__PURE__*/ l.procedure($nsid, $params, $input, $output, [
  'InvalidRequest',
  'Forbidden',
])

export { main }

export const $lxm = $nsid
