/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'com.publicdomainrelay.temp.market.relays'

export { $nsid }

/** List of AT Protocol relay URLs that the record owner recommends for market discovery. Requesters read this record via autoDiscoverRelayUrls to find relays to query for bidder offerings. */
type Main = {
  $type: 'com.publicdomainrelay.temp.market.relays'

  /**
   * AT Protocol relay HTTP(S) URLs to use for market participant discovery.
   */
  relays: l.UriString[]
  createdAt: l.DatetimeString
}

export type { Main }

/** List of AT Protocol relay URLs that the record owner recommends for market discovery. Requesters read this record via autoDiscoverRelayUrls to find relays to query for bidder offerings. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    relays: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'uri' }), {
      minLength: 1,
    }),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
