const ENTRY = "lib/market-policy-engine-worker/policy-entry.ts";
const OUT = "lib/market-policy-engine-worker/builtin-bundle.ts";

const tmp = await Deno.makeTempFile({ suffix: ".js" });

const cmd = new Deno.Command("deno", {
  args: ["bundle", "--quiet", "--platform", "browser", "-o", tmp, ENTRY],
  stdout: "piped",
  stderr: "piped",
});
const out = await cmd.output();
if (!out.success) {
  console.error(new TextDecoder().decode(out.stderr));
  Deno.exit(1);
}

const bundleJs = await Deno.readTextFile(tmp);
await Deno.remove(tmp).catch(() => {});

const header = "// GENERATED by scripts/build-policy-bundle.ts. DO NOT EDIT.\n" +
  "// Standalone bundle of the first-party policy registry, executed inside the\n" +
  "// deno-worker-sandbox with no permissions.\n";

await Deno.writeTextFile(
  OUT,
  `${header}export const BUILTIN_POLICY_BUNDLE = ${JSON.stringify(bundleJs)};\n`,
);

console.log(`wrote ${OUT} (${bundleJs.length} bytes of bundled JS)`);
