apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: hono-bidder
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
  - sc.lib-abc-market-bidder
  - sc.lib-atproto-helpers
  - sc.lib-atproto-oauth-helpers
  - sc.lib-common-market-common
  - sc.lib-did-key-ingress-proxy
  - sc.lib-did-plc
  - sc.lib-market-atproto
  - sc.lib-market-bidder
  - sc.lib-market-bidder-compute
  - sc.lib-market-bidder-worker
  - sc.lib-requester-xrpc
codeRefIndex:
- file:hono-bidder/cli-args-env.ts cli-args-env.ts@hono-bidder/cli-args-env.ts
- file:hono-bidder/mod.ts mod.ts@hono-bidder/mod.ts
