apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-market-bidder-worker
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
  - sc.lib-abc-market
  - sc.lib-abc-market-bidder
  - sc.lib-atproto-attestation-port
  - sc.lib-atproto-helpers
  - sc.lib-common-market-common
  - sc.lib-market-atproto
codeRefIndex:
- file:lib/market-bidder-worker/mod.ts mod.ts@lib/market-bidder-worker/mod.ts
