apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/common/market-lexicons/com/atproto/repo/strongRef.defs.ts strongRef.defs.ts@lib/common/market-lexicons/com/atproto/repo/strongRef.defs.ts
- file:lib/common/market-lexicons/com/atproto/repo/strongRef.ts strongRef.ts@lib/common/market-lexicons/com/atproto/repo/strongRef.ts
kind: SystemContext
metadata:
  name: lib-common-market-lexicons-com-atproto-repo
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
