apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-hono-factory-secrets-oidc
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
  - sc.lib-common-secrets-common
  - sc.lib-secrets-oidc
codeRefIndex:
- file:lib/hono-factory-secrets-oidc/mod.ts mod.ts@lib/hono-factory-secrets-oidc/mod.ts
