apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/did-key-ingress-proxy/mod.ts mod.ts@lib/did-key-ingress-proxy/mod.ts
kind: SystemContext
metadata:
  name: lib-did-key-ingress-proxy
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
