apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-compute-contract-gateway-xrpc
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
  - sc.lib-abc-compute-contract-gateway
  - sc.lib-abc-requester
  - sc.lib-common-compute-contract-gateway-common
codeRefIndex:
- file:lib/compute-contract-gateway-xrpc/mod.ts mod.ts@lib/compute-contract-gateway-xrpc/mod.ts
