apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/hono-factory-market-settlement-x402/mod.ts mod.ts@lib/hono-factory-market-settlement-x402/mod.ts
kind: SystemContext
metadata:
  name: lib-hono-factory-market-settlement-x402
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
