apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/market-bidder/mod.ts mod.ts@lib/market-bidder/mod.ts
kind: SystemContext
metadata:
  name: lib-market-bidder
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
