apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/common/market-lexicons/com/publicdomainrelay/temp/requester/associateConfirm.defs.ts
  associateConfirm.defs.ts@lib/common/market-lexicons/com/publicdomainrelay/temp/requester/associateConfirm.defs.ts
- file:lib/common/market-lexicons/com/publicdomainrelay/temp/requester/associateConfirm.ts
  associateConfirm.ts@lib/common/market-lexicons/com/publicdomainrelay/temp/requester/associateConfirm.ts
kind: SystemContext
metadata:
  name: lib-common-market-lexicons-com-publicdomainrelay-temp-requester
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
