apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/common/market-lexicons/com/publicdomainrelay/temp/tangled/spindle.ts spindle.ts@lib/common/market-lexicons/com/publicdomainrelay/temp/tangled/spindle.ts
kind: SystemContext
metadata:
  name: lib-common-market-lexicons-com-publicdomainrelay-temp-tangled
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
