apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/guest-capability-secrets/mod.ts mod.ts@lib/guest-capability-secrets/mod.ts
kind: SystemContext
metadata:
  name: lib-guest-capability-secrets
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
