apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-guest-capability-secrets
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
  - sc.lib-abc-guest-capability
  - sc.lib-common-secrets-common
  - sc.lib-did-key-ingress-proxy
  - sc.lib-hono-factory-secrets-oidc
  - sc.lib-secrets-oidc
codeRefIndex:
- file:lib/guest-capability-secrets/mod.ts mod.ts@lib/guest-capability-secrets/mod.ts
