apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/hono-factory-did-plc-directory/storage/plc-store.ts plc-store.ts@lib/hono-factory-did-plc-directory/storage/plc-store.ts
kind: SystemContext
metadata:
  name: lib-hono-factory-did-plc-directory-storage
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
