apiVersion: specs.publicdomainrelay.dev/v1alpha1
codeRefIndex:
- file:lib/hono-factory-compute-contract-gateway-xrpc/mod.ts mod.ts@lib/hono-factory-compute-contract-gateway-xrpc/mod.ts
kind: SystemContext
metadata:
  name: lib-hono-factory-compute-contract-gateway-xrpc
  namespace: default
spec:
  dependsOn:
  - sc.atproto-market
  repository: atproto-market
  upstream: self
