apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-trust-graph-tangled-graph
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
  - sc.lib-abc-trust-graph
  - sc.lib-common-market-common
codeRefIndex:
- file:lib/trust-graph-tangled-graph/mod.ts mod.ts@lib/trust-graph-tangled-graph/mod.ts
