apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-cocore-api
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
codeRefIndex:
- file:lib/cocore-api/mod.ts mod.ts@lib/cocore-api/mod.ts
