apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: lib-common-secrets-common
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
codeRefIndex:
- file:lib/common/secrets-common/mod.ts mod.ts@lib/common/secrets-common/mod.ts
