apiVersion: specs.publicdomainrelay.dev/v1alpha1
kind: SystemContext
metadata:
  name: request-vm-ssh
  namespace: default
spec:
  repository: atproto-market
  upstream: self
  dependsOn:
  - sc.atproto-market
  - sc.lib-abc-guest-capability
  - sc.lib-abc-requester
  - sc.lib-atproto-helpers
  - sc.lib-atproto-oauth-helpers
  - sc.lib-common-market-common
  - sc.lib-common-secrets-common
  - sc.lib-did-plc
  - sc.lib-guest-capability-secrets
  - sc.lib-requester-xrpc
codeRefIndex:
- file:request-vm-ssh/cli-args-env.ts cli-args-env.ts@request-vm-ssh/cli-args-env.ts
- file:request-vm-ssh/cli_smoke_test.ts cli_smoke_test.ts@request-vm-ssh/cli_smoke_test.ts
- file:request-vm-ssh/mod.ts mod.ts@request-vm-ssh/mod.ts
